---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app2
  namespace: default
  labels:
    app: nodejs-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app2
  template:
    metadata:
      labels:
        app: nodejs-app2
    spec:
      containers:
      - name: nodejs-app2
        image: "rushidockerhub1881/myapp2:latest"
        resources:
          limits:
            memory: "450Mi"
            cpu: "700m"
        ports:
          - containerPort: 3000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-192-168-48-211.ap-south-1.compute.internal   
      
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app2
  namespace: default
spec:
  selector:
    app: nodejs-app2
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
